const Terms = () => {
  const sections = [
    { title: "Acceptance of Terms", content: "By accessing or using TVK Tools, you agree to be bound by these Terms & Conditions. If you do not agree, please do not use our services." },
    { title: "Description of Service", content: "TVK Tools provides a platform of AI-powered and utility tools for SEO, development, content creation, and general productivity. Some tools are available for free, while others require a paid subscription." },
    { title: "User Accounts", content: "You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information and to update it as necessary. You must be at least 13 years old to use our services." },
    { title: "Acceptable Use", content: "You agree not to use our tools for any illegal, harmful, or abusive purposes. You may not attempt to reverse-engineer, exploit, or interfere with our services. Automated scraping or excessive API usage without authorization is prohibited." },
    { title: "Intellectual Property", content: "The TVK Tools platform, including its design, code, and content, is owned by TVK Tools. Output generated by our tools belongs to you, but we retain the right to use anonymized usage data to improve our services." },
    { title: "Free and Paid Plans", content: "Free plan users have limited tool access and usage limits. Paid plans provide expanded access as described on our pricing page. We reserve the right to modify plan features and pricing with reasonable notice." },
    { title: "API Usage", content: "API access is provided to Pro and Enterprise plan users. API keys are personal and must not be shared. We reserve the right to rate-limit or suspend API access for excessive or abusive usage." },
    { title: "Limitation of Liability", content: "TVK Tools is provided 'as is' without warranties. We are not liable for any damages arising from your use of our services, including loss of data or business interruption." },
    { title: "Termination", content: "We may suspend or terminate your account if you violate these terms. You may delete your account at any time from your dashboard settings." },
    { title: "Changes to Terms", content: "We may update these terms from time to time. Continued use of our services after changes constitutes acceptance of the new terms." },
    { title: "Contact", content: "For questions about these terms, contact us at support@tvktools.com." },
  ];

  return (
    <div className="cyber-grid min-h-screen py-16">
      <div className="container mx-auto max-w-3xl px-4">
        <h1 className="font-heading text-3xl font-bold text-primary neon-text">Terms & Conditions</h1>
        <p className="mt-2 text-xs text-muted-foreground">Last updated: March 2026</p>

        <div className="mt-8 space-y-8">
          {sections.map((section, i) => (
            <section key={i}>
              <h2 className="font-heading text-sm font-bold text-foreground">{i + 1}. {section.title}</h2>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{section.content}</p>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Terms;
